//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyPhase.Chat.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase
    {
        public Phase()
        {
            this.Projects = new HashSet<Project>();
            this.ProjectTaskPhases = new HashSet<ProjectTaskPhase>();
            this.Tasks = new HashSet<Task>();
            this.Users = new HashSet<User>();
            this.Users1 = new HashSet<User>();
            this.Projects1 = new HashSet<Project>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Position { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<ProjectTaskPhase> ProjectTaskPhases { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<User> Users1 { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
    }
}
