//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyPhase.Chat.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTaskPhase
    {
        public int ProjectID { get; set; }
        public int PhaseID { get; set; }
        public bool Active { get; set; }
    
        public virtual Phase Phase { get; set; }
    }
}
