//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyPhase.Chat.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Labels = new HashSet<Label>();
            this.ProjectHistories = new HashSet<ProjectHistory>();
            this.TeamProjects = new HashSet<TeamProject>();
            this.Phases = new HashSet<Phase>();
            this.Tasks = new HashSet<Task>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PhaseID { get; set; }
        public Nullable<System.DateTime> EstStartDate { get; set; }
        public Nullable<System.DateTime> EstEndDate { get; set; }
        public Nullable<System.DateTime> ActStartDate { get; set; }
        public Nullable<System.DateTime> ActEndDate { get; set; }
        public Nullable<double> Budget { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Label> Labels { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual ICollection<ProjectHistory> ProjectHistories { get; set; }
        public virtual ICollection<TeamProject> TeamProjects { get; set; }
        public virtual ICollection<Phase> Phases { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
